apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    chapter: deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      name: myapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
  template:
    metadata:
      labels:
        name: myapp
        chapter: deployment
    spec:
      containers:
      - name: myapp
        image: ghcr.io/mmorejon/erase-una-vez-1:v0.3.0
        env:
        - name: SLEEP_TIME
          value: "10s"
